---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Tim Stachowski's Personal Website"
keywords:    "Tim Stachowski, PhD"
description: "Personal website for my research, code, and hobbies"
source_link: "https://github.com/t413/SinglePaged"
favicon:     lightbulb-o
touch_icon:  lightbulb-o
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#ffffff'
  blue:      '#256697'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  grey:      '#f2f2f2'
  forest:    '#0D7120'

kramdown:
  auto_ids:  false

